// <auto-generated />
using System;
using MccPortfolio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MccPortfolio.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605052220_AddRegNumberAndProfilePic")]
    partial class AddRegNumberAndProfilePic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MccPortfolio.Api.Entities.AISuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("AISuggestions");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-4444-4444-4444-111111111111"),
                            Category = "Competition",
                            Date = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Won first place out of 80 teams for proposing and coding a smart traffic diversion grid using edge computing.",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555"),
                            Title = "1st Place - Chennai Inter-Collegiate Smart City Hackathon"
                        },
                        new
                        {
                            Id = new Guid("55555555-4444-4444-4444-222222222222"),
                            Category = "Olympiad",
                            Date = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Achieved percentile rank of 99.8% in cybersecurity analytics assessment.",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555"),
                            Title = "Rank 152 in National Cyber Olympiad"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CredentialUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111111"),
                            CredentialId = "AWS-SAA-1092837",
                            CredentialUrl = "https://aws.amazon.com",
                            FileUrl = "",
                            IssueDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Issuer = "Amazon Web Services",
                            Name = "AWS Certified Solutions Architect – Associate",
                            Status = "verified",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555")
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-222222222222"),
                            CredentialId = "AZ-204-890217",
                            CredentialUrl = "https://microsoft.com",
                            FileUrl = "",
                            IssueDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Issuer = "Microsoft",
                            Name = "Microsoft Certified: Azure Developer Associate",
                            Status = "verified",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555")
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.CommunityService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HoursServed")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("CommunityServices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-6666-6666-6666-111111111111"),
                            Activity = "Digital Literacy Campaign",
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Taught basic computer operations, internet safety, and banking security to over 150 school children and seniors in nearby villages.",
                            HoursServed = 60,
                            OrganizationName = "MCC National Service Scheme (NSS)",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555")
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.CreativeWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BehanceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("CreativeWorks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-7777-7777-7777-111111111111"),
                            BehanceUrl = "https://behance.net/gallery/scrub-jungle",
                            Description = "A visual exploration of MCC's unique biodiversity, showcasing flora and fauna captured over four seasons.",
                            MediaUrl = "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555"),
                            Title = "MCC Scrub Jungle Photography Exhibition"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "CS",
                            InstitutionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-333333333333"),
                            Code = "COM",
                            InstitutionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Commerce"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-444444444444"),
                            Code = "CHEM",
                            InstitutionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Chemistry"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Hackathon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Hackathons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-111111111111"),
                            AchievementPosition = "Winner",
                            Date = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A 36-hour sprint creating decentralized medical record portals.",
                            Name = "DevHacks Chennai 2025",
                            ProjectName = "MediSync",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555")
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Tambaram East, Chennai, Tamil Nadu 600059",
                            Code = "MCC",
                            ContactEmail = "info@mcc.edu.in",
                            Name = "Madras Christian College"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.PortfolioApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("PortfolioApprovals");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LiveDemoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-3333-3333-3333-111111111111"),
                            Description = "A real-time WebApp using Leaflet.js and ASP.NET Core that maps MCC's 365-acre scrub jungle campus and manages registrations for inter-collegiate cultural festivals.",
                            GitHubUrl = "https://github.com/franklinraj/mcc-navigator",
                            LiveDemoUrl = "https://mccnavigator.demo.in",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555"),
                            TechStack = "React;Tailwind CSS;.NET Web API;PostgreSQL;LeafletJS",
                            Title = "MCC Campus Navigator & Event Planner"
                        },
                        new
                        {
                            Id = new Guid("55555555-3333-3333-3333-222222222222"),
                            Description = "A hackathon-winning application that secures patient medical files using decentralized storage, verified via public-key cryptography.",
                            GitHubUrl = "https://github.com/franklinraj/medisync",
                            LiveDemoUrl = "https://medisync.demo.in",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555"),
                            TechStack = "Next.js;Solidity;Ethers.js;Node.js;Express",
                            Title = "MediSync - Decentralized Electronic Health Records"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.ResearchPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsInnovationProject")
                        .HasColumnType("boolean");

                    b.Property<string>("JournalOrConference")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PaperUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrototypeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartupIdeaPitch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("ResearchPapers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-2222-2222-2222-111111111111"),
                            Abstract = "This paper presents a convolutional neural network (CNN) model optimized for low-compute mobile devices to identify leaf-spot diseases in Tamil Nadu agricultural sectors with 96.4% validation accuracy.",
                            IsInnovationProject = true,
                            JournalOrConference = "IEEE International Conference on Agrotechnology & AI (ICAAI 2025)",
                            PaperUrl = "https://ieee.org",
                            PrototypeStatus = "Prototype",
                            PublishDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartupIdeaPitch = "AgriScan AI: An app enabling farmers to snap pictures of crop leaves and receive instant organic remedies, bypassing middleman consulting fees.",
                            StudentProfileId = new Guid("44444444-4444-4444-4444-555555555555"),
                            Title = "Leveraging Deep Neural Networks for Plant Disease Detection in South Indian Crops"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicRecordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BehanceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomThemeConfig")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalStory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QRCodeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatementOfPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsernameSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AcademicRecordsJson = "[{\"degree\":\"B.Sc. Computer Science\",\"institution\":\"Madras Christian College\",\"cgpa\":\"8.5\",\"year\":\"2026\"}]",
                            BehanceUrl = "",
                            Bio = "Aspiring Software Engineer studying Computer Science at MCC.",
                            CustomThemeConfig = "{}",
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            GitHubUrl = "https://github.com",
                            Headline = "Computer Science Student | Web Enthusiast",
                            IsApproved = true,
                            LinkedInUrl = "https://linkedin.com",
                            PersonalStory = "My journey began with basic HTML and has grown into building modern web services.",
                            ProfilePictureUrl = "",
                            QRCodeUrl = "",
                            RegistrationNumber = "",
                            ResumeUrl = "",
                            Skills = "React;Next.js;C#;.NET;SQL",
                            StatementOfPurpose = "To research and build scalable architectures that solve community problems.",
                            Theme = "Apple-Minimal",
                            UserId = new Guid("33333333-3333-3333-3333-444444444444"),
                            UsernameSlug = "student"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-555555555555"),
                            AcademicRecordsJson = "[{\"degree\":\"B.Sc. Computer Science\",\"institution\":\"Madras Christian College\",\"cgpa\":\"9.2\",\"year\":\"2026\"}]",
                            BehanceUrl = "https://behance.net/franklinraj",
                            Bio = "Passionate tech innovator, Full-Stack Developer, and undergraduate researcher at Madras Christian College. Building solutions at the intersection of AI, Web Technologies, and Social Good.",
                            CustomThemeConfig = "{}",
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            GitHubUrl = "https://github.com/franklinraj",
                            Headline = "Undergraduate Researcher & Full-Stack Engineer | President, MCC Computer Club",
                            IsApproved = true,
                            LinkedInUrl = "https://linkedin.com/in/franklinraj",
                            PersonalStory = "Ever since I compiled my first 'Hello World' on the historic MCC campus, I've been fascinated by how software can impact society. Over the last three years, I have worked with local NGOs, organized hackathons, and published research papers on deep learning models.",
                            ProfilePictureUrl = "",
                            QRCodeUrl = "",
                            RegistrationNumber = "",
                            ResumeUrl = "",
                            Skills = "Next.js;React;ASP.NET Core;PostgreSQL;Tailwind CSS;Framer Motion;Python;TypeScript;Docker",
                            StatementOfPurpose = "To pursue advanced studies in Artificial Intelligence and build robust web tools that democratize access to education and resource management for public institutions.",
                            Theme = "AI-Futuristic",
                            UserId = new Guid("33333333-3333-3333-3333-555555555555"),
                            UsernameSlug = "franklinraj"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@mcc.edu",
                            Name = "Dr. Paul Wilson",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-444444444444"),
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@mcc.edu",
                            Name = "Default Student",
                            PasswordHash = "JkyMOBvxbJgqTlmw3UxveAjFGgX2TDXbQsx4oqcodbs=",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "franklinraj@mcc.edu",
                            Name = "Franklin Raj",
                            PasswordHash = "JkyMOBvxbJgqTlmw3UxveAjFGgX2TDXbQsx4oqcodbs=",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.AISuggestion", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("AISuggestions")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Achievement", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Achievements")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Certification", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Certifications")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.CommunityService", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("CommunityServices")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.CreativeWork", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("CreativeWorks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Department", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.Institution", "Institution")
                        .WithMany("Departments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Hackathon", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Hackathons")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Notification", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.PortfolioApproval", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.User", "ReviewedBy")
                        .WithMany("ReviewedApprovals")
                        .HasForeignKey("ReviewedById");

                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Approvals")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedBy");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Project", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Projects")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.ResearchPaper", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ResearchPapers")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.StudentProfile", b =>
                {
                    b.HasOne("MccPortfolio.Api.Entities.Department", "Department")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MccPortfolio.Api.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("MccPortfolio.Api.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Department", b =>
                {
                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.Institution", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.StudentProfile", b =>
                {
                    b.Navigation("AISuggestions");

                    b.Navigation("Achievements");

                    b.Navigation("Approvals");

                    b.Navigation("Certifications");

                    b.Navigation("CommunityServices");

                    b.Navigation("CreativeWorks");

                    b.Navigation("Hackathons");

                    b.Navigation("Projects");

                    b.Navigation("ResearchPapers");
                });

            modelBuilder.Entity("MccPortfolio.Api.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ReviewedApprovals");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
